#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Configure environment variables for llama-webui on Windows
.DESCRIPTION
    This script detects the llama-server binary and sets up environment variables.
    It can also create a .env file for persistent configuration.
.PARAMETER CreateEnvFile
    Create a .env file in the project root
.PARAMETER LlamaServerPath
    Explicit path to llama-server executable (optional, auto-detected if not provided)
.EXAMPLE
    .\configure_env.ps1
.EXAMPLE
    .\configure_env.ps1 -CreateEnvFile
#>
[CmdletBinding()]
param(
    [switch]$CreateEnvFile,
    [string]$LlamaServerPath = ""
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$LlamaDir = Join-Path $RepoRoot "third_party" "llama.cpp"

Write-Host "=== llama-webui Environment Configuration ===" -ForegroundColor Cyan
Write-Host ""

# Auto-detect llama-server
$SearchPaths = @()

if ($LlamaServerPath -and (Test-Path $LlamaServerPath)) {
    $SearchPaths += $LlamaServerPath
} else {
    # Common build locations
    $SearchPaths += Join-Path $LlamaDir "build-cuda\bin\Release\llama-server.exe"
    $SearchPaths += Join-Path $LlamaDir "build-cuda\bin\llama-server.exe"
    $SearchPaths += Join-Path $LlamaDir "prebuilt\llama-server.exe"
    $SearchPaths += Join-Path $LlamaDir "build\bin\Release\llama-server.exe"
    $SearchPaths += Join-Path $LlamaDir "build\bin\llama-server.exe"
}

$ServerExe = $null
foreach ($path in $SearchPaths) {
    if (Test-Path $path) {
        $ServerExe = $path
        break
    }
}

if (-not $ServerExe) {
    Write-Warning "llama-server.exe not found. Please build llama.cpp first or specify the path."
    Write-Host ""
    Write-Host "To build, run: .\scripts\build_llama_cuda.ps1" -ForegroundColor Yellow
    exit 1
}

Write-Host "Found llama-server.exe: $ServerExe" -ForegroundColor Green

# Set environment variable
$env:LLAMA_WEBUI_LLAMA_SERVER = $ServerExe
[System.Environment]::SetEnvironmentVariable("LLAMA_WEBUI_LLAMA_SERVER", $ServerExe, "User")

Write-Host ""
Write-Host "Environment variable set:" -ForegroundColor Yellow
Write-Host "  LLAMA_WEBUI_LLAMA_SERVER = $ServerExe" -ForegroundColor Cyan

# Set other useful variables
$ModelsDir = Join-Path $RepoRoot "models"
if (-not (Test-Path $ModelsDir)) {
    New-Item -ItemType Directory -Path $ModelsDir | Out-Null
    Write-Host "Created models directory: $ModelsDir" -ForegroundColor Green
}

$env:LLAMA_WEBUI_MODEL_DIRS = $ModelsDir
[System.Environment]::SetEnvironmentVariable("LLAMA_WEBUI_MODEL_DIRS", $ModelsDir, "User")

$DataDir = Join-Path $RepoRoot "data"
if (-not (Test-Path $DataDir)) {
    New-Item -ItemType Directory -Path $DataDir | Out-Null
}

$env:LLAMA_WEBUI_DATA_DIR = $DataDir
[System.Environment]::SetEnvironmentVariable("LLAMA_WEBUI_DATA_DIR", $DataDir, "User")

Write-Host "  LLAMA_WEBUI_MODEL_DIRS = $ModelsDir" -ForegroundColor Cyan
Write-Host "  LLAMA_WEBUI_DATA_DIR = $DataDir" -ForegroundColor Cyan

# Create .env file if requested
if ($CreateEnvFile) {
    $EnvFile = Join-Path $RepoRoot ".env"
    $EnvContent = @"
# llama-webui configuration
# Generated by configure_env.ps1 on $(Get-Date)

LLAMA_WEBUI_LLAMA_SERVER=$ServerExe
LLAMA_WEBUI_MODEL_DIRS=$ModelsDir
LLAMA_WEBUI_DATA_DIR=$DataDir
LLAMA_WEBUI_DEFAULT_DOWNLOAD_DIR=$ModelsDir
"@
    
    Set-Content -Path $EnvFile -Value $EnvContent
    Write-Host ""
    Write-Host "Created .env file: $EnvFile" -ForegroundColor Green
}

Write-Host ""
Write-Host "Environment configured successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "You can now run:" -ForegroundColor Yellow
Write-Host "  llama-webui" -ForegroundColor Gray
Write-Host ""
Write-Host "Or activate the virtual environment first:" -ForegroundColor Yellow
Write-Host "  .venv\Scripts\Activate.ps1" -ForegroundColor Gray
Write-Host "  llama-webui" -ForegroundColor Gray
